In [3]:
import os

# Ruta de la carpeta principal
base_path = r'C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas'

# Recorrer todos los directorios y archivos dentro de base_path
for root, dirs, files in os.walk(base_path):
    for filename in files:
        # Comprobar si el archivo tiene la extensión .xlsx
        if filename.endswith('.xlsx'):
            print(f'Archivo encontrado: {os.path.join(root, filename)}')

Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\AD\AR_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\AD\Bra_USP_AD_processed_SourceTransformation_ODQ_metrics - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\AD\CH_AD_processed_SourceTransformation_ODQ_metrics - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\AD\COL_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\AD\Tur_IUEFM_AD_processed_SourceTransformation_ODQ_metrics - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\CN\aperiodic_jhosmary_03.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\FTD\ARG_FTD_processed_SourceTransformation_ODQ_metrics - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\FTD\CH_FTD_processed_SourceTransformation_ODQ_metrics - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\FTD\Col_processed_SourceTransformation_ODQ_metrics - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\MCI\Col_MCI_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\MCI\Tur_IUEFM_MCI_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\PD\ARG_F17_PD_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\PD\CH_F17_PD_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\PD\CH_Taknew_PD_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\PD\CH_Tak_new2_PD_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Aperiodic\PD\CH_Tak_new3_PD_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\AD\AR_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\AD\Ch_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\AD\Col_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\AD\Tur_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\AD\USP_processed_SourceTransformation_AD_Complexity_metrics_ODQ.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\CN\complexity_jhos_30.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\FTD\ARG_processed_SourceTransformation_FTD_ODQ_metrics - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\FTD\CH_processed_SourceTransformation_FTD_ODQ_metrics - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\FTD\Col_processed_SourceTransformation_FTD_ODQ_metrics - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\MCI\Col_USCO_processed_SourceTransformation_MCI_ODQ_metrics - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\MCI\Tur_IUEFM_processed_SourceTransformation_DCL_ODQ_metrics - copia.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\PD\AR_F17_PD_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Complex\PD\CH_PD_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\AD\AD_ARG_freq.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\AD\AD_Col_freq.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\AD\Bra_USP_AD_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\AD\CH_freq.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\AD\Tur_IUEFM_AD_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\CN\frecuency_jhos_.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\FTD\ARG_FTD_freq.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\FTD\CH_FTD_freq.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\FTD\Tak_Col_Bog_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\MCI\Col_MCI_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\MCI\Tur_IUEFM_MCI_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\PD\ARG_F17_PD_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\PD\Chile_Takeda_new_PD_SourceTransformation_PD_Frecuency_metrics_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\PD\CH_F17_Frecuency_metrics_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\PD\CH_Tak_new2_PD_processed_SourceTransformation_ODQ_metrics.xlsx
Archivo encontrado: C:\Users\felip\OneDrive - Universidad Técnica Federico Santa María\Documentos\Brain\Multiple_Brain_Age_Clocks\metricas\Freq\PD\CH_Tak_new3_PD_processed_SourceTransformation_ODQ_metrics.xlsx

In [ ]:
path_aperiodic = 'C:/Users/felip/OneDrive - Universidad Técnica Federico Santa María/Documentos/Brain/Multiple_Brain_Age_Clocks/metricas/Aperiodic/'
path_complex = 'C:/Users/felip/OneDrive - Universidad Técnica Federico Santa María/Documentos/Brain/Multiple_Brain_Age_Clocks/metricas/Complex/'
path_freq = 'C:/Users/felip/OneDrive - Universidad Técnica Federico Santa María/Documentos/Brain/Multiple_Brain_Age_Clocks/metricas/Freq/'

In [7]:
path_aperiodic = 'C:/Users/felipe/OneDrive - Universidad Técnica Federico Santa María/Documentos/Brain/Multiple_Brain_Age_Clocks/metricas/Aperiodic/'
path_complex = 'C:/Users/felipe/OneDrive - Universidad Técnica Federico Santa María/Documentos/Brain/Multiple_Brain_Age_Clocks/metricas/Complex/'
path_freq = 'C:/Users/felipe/OneDrive - Universidad Técnica Federico Santa María/Documentos/Brain/Multiple_Brain_Age_Clocks/metricas/Freq/'

In [3]:
import pandas as pd

In [34]:
import pandas as pd
# Ruta principal
path_aperiodic = 'C:/Users/felip/OneDrive - Universidad Técnica Federico Santa María/Documentos/Brain/Multiple_Brain_Age_Clocks/metricas/Aperiodic/'

# Leer archivos y asignar a variables

# Directorio AD
df_AD_arg_aperiodic = pd.read_excel(f"{path_aperiodic}AD/AR_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx")
df_AD_bra_aperiodic = pd.read_excel(f"{path_aperiodic}AD/Bra_USP_AD_processed_SourceTransformation_ODQ_metrics - copia.xlsx")
df_AD_ch_aperiodic = pd.read_excel(f"{path_aperiodic}AD/CH_AD_processed_SourceTransformation_ODQ_metrics - copia.xlsx")
df_AD_col_aperiodic = pd.read_excel(f"{path_aperiodic}AD/COL_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx")
df_AD_tur_aperiodic = pd.read_excel(f"{path_aperiodic}AD/Tur_IUEFM_AD_processed_SourceTransformation_ODQ_metrics - copia.xlsx")

# Directorio CN
df_CN_aperiodic = pd.read_excel(f"{path_aperiodic}CN/aperiodic_jhosmary_03.xlsx")

# Directorio FTD
df_FTD_arg_aperiodic = pd.read_excel(f"{path_aperiodic}FTD/ARG_FTD_processed_SourceTransformation_ODQ_metrics - copia.xlsx")
df_FTD_ch_aperiodic = pd.read_excel(f"{path_aperiodic}FTD/CH_FTD_processed_SourceTransformation_ODQ_metrics - copia.xlsx")
df_FTD_col_aperiodic = pd.read_excel(f"{path_aperiodic}FTD/Col_processed_SourceTransformation_ODQ_metrics - copia.xlsx")

# Directorio MCI
df_MCI_col_aperiodic = pd.read_excel(f"{path_aperiodic}MCI/Col_MCI_processed_SourceTransformation_ODQ_metrics.xlsx")
df_MCI_tur_aperiodic = pd.read_excel(f"{path_aperiodic}MCI/Tur_IUEFM_MCI_processed_SourceTransformation_ODQ_metrics.xlsx")

# Directorio PD
df_PD_arg_aperiodic = pd.read_excel(f"{path_aperiodic}PD/ARG_F17_PD_processed_SourceTransformation_ODQ_metrics.xlsx")
df_PD_chile_aperiodic = pd.read_excel(f"{path_aperiodic}PD/CH_Taknew_PD_processed_SourceTransformation_ODQ_metrics.xlsx")
df_PD_ch_f17_aperiodic = pd.read_excel(f"{path_aperiodic}PD/CH_F17_PD_processed_SourceTransformation_ODQ_metrics.xlsx")
df_PD_ch_new2_aperiodic = pd.read_excel(f"{path_aperiodic}PD/CH_Tak_new2_PD_processed_SourceTransformation_ODQ_metrics.xlsx")
df_PD_ch_new3_aperiodic = pd.read_excel(f"{path_aperiodic}PD/CH_Tak_new3_PD_processed_SourceTransformation_ODQ_metrics.xlsx")

In [35]:
import pandas as pd

# Ruta principal
path_complex = 'C:/Users/felip/OneDrive - Universidad Técnica Federico Santa María/Documentos/Brain/Multiple_Brain_Age_Clocks/metricas/Complex/'

# Directorio AD
df_AD_arg_complex = pd.read_excel(f"{path_complex}AD/AR_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx")
df_AD_ch_complex = pd.read_excel(f"{path_complex}AD/Ch_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx")
df_AD_col_complex = pd.read_excel(f"{path_complex}AD/Col_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx")
df_AD_tur_complex = pd.read_excel(f"{path_complex}AD/Tur_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx")
df_AD_usp_complex = pd.read_excel(f"{path_complex}AD/USP_processed_SourceTransformation_AD_Complexity_metrics_ODQ.xlsx")

# Directorio CN
df_CN_complex = pd.read_excel(f"{path_complex}CN/complexity_jhos_30.xlsx")

# Directorio FTD
df_FTD_arg_complex = pd.read_excel(f"{path_complex}FTD/ARG_processed_SourceTransformation_FTD_ODQ_metrics - copia.xlsx")
df_FTD_ch_complex = pd.read_excel(f"{path_complex}FTD/CH_processed_SourceTransformation_FTD_ODQ_metrics - copia.xlsx")
df_FTD_col_complex = pd.read_excel(f"{path_complex}FTD/Col_processed_SourceTransformation_FTD_ODQ_metrics - copia.xlsx")

# Directorio MCI
df_MCI_col_complex = pd.read_excel(f"{path_complex}MCI/Col_USCO_processed_SourceTransformation_MCI_ODQ_metrics - copia.xlsx")
df_MCI_tur_complex = pd.read_excel(f"{path_complex}MCI/Tur_IUEFM_processed_SourceTransformation_DCL_ODQ_metrics - copia.xlsx")

# Directorio PD
df_PD_arg_complex = pd.read_excel(f"{path_complex}PD/AR_F17_PD_processed_SourceTransformation_ODQ_metrics.xlsx")
df_PD_ch_complex = pd.read_excel(f"{path_complex}PD/CH_PD_processed_SourceTransformation_ODQ_metrics.xlsx")

In [36]:
import pandas as pd

# Ruta principal
path_freq = 'C:/Users/felip/OneDrive - Universidad Técnica Federico Santa María/Documentos/Brain/Multiple_Brain_Age_Clocks/metricas/Freq/'

# Directorio AD
df_AD_arg_freq = pd.read_excel(f"{path_freq}AD/AD_ARG_freq.xlsx")
df_AD_col_freq = pd.read_excel(f"{path_freq}AD/AD_Col_freq.xlsx")
df_AD_bra_freq = pd.read_excel(f"{path_freq}AD/Bra_USP_AD_processed_SourceTransformation_ODQ_metrics.xlsx")
df_AD_ch_freq = pd.read_excel(f"{path_freq}AD/CH_freq.xlsx")
df_AD_tur_freq = pd.read_excel(f"{path_freq}AD/Tur_IUEFM_AD_processed_SourceTransformation_ODQ_metrics.xlsx")

# Directorio CN
df_CN_freq = pd.read_excel(f"{path_freq}CN/frecuency_jhos_.xlsx")

# Directorio FTD
df_FTD_arg_freq = pd.read_excel(f"{path_freq}FTD/ARG_FTD_freq.xlsx")
df_FTD_ch_freq = pd.read_excel(f"{path_freq}FTD/CH_FTD_freq.xlsx")
df_FTD_tak_freq = pd.read_excel(f"{path_freq}FTD/Tak_Col_Bog_processed_SourceTransformation_ODQ_metrics.xlsx")

# Directorio MCI
df_MCI_col_freq = pd.read_excel(f"{path_freq}MCI/Col_MCI_processed_SourceTransformation_ODQ_metrics.xlsx")
df_MCI_tur_freq = pd.read_excel(f"{path_freq}MCI/Tur_IUEFM_MCI_processed_SourceTransformation_ODQ_metrics.xlsx")

# Directorio PD
df_PD_arg_freq = pd.read_excel(f"{path_freq}PD/ARG_F17_PD_processed_SourceTransformation_ODQ_metrics.xlsx")
df_PD_chile_freq = pd.read_excel(f"{path_freq}PD/Chile_Takeda_new_PD_SourceTransformation_PD_Frecuency_metrics_ODQ_metrics.xlsx")
df_PD_ch1_freq = pd.read_excel(f"{path_freq}PD/CH_F17_Frecuency_metrics_ODQ_metrics.xlsx")
df_PD_ch2_freq = pd.read_excel(f"{path_freq}PD/CH_Tak_new2_PD_processed_SourceTransformation_ODQ_metrics.xlsx")
df_PD_ch3_freq = pd.read_excel(f"{path_freq}PD/CH_Tak_new3_PD_processed_SourceTransformation_ODQ_metrics.xlsx")

# CN

In [5]:
# Directorio CN
df_CN_aperiodic = pd.read_excel(f"{path_aperiodic}CN/aperiodic_jhosmary_03.xlsx")
df_CN_complex = pd.read_excel(f"{path_complex}CN/complexity_jhos_30.xlsx")
df_CN_freq = pd.read_excel(f"{path_freq}CN/frecuency_jhos_.xlsx")
print(df_CN_aperiodic.shape, df_CN_complex.shape, df_CN_freq.shape)

(1383, 42) (1383, 20) (1384, 227)

In [6]:
# Extraemos las listas de identificadores de cada DataFrame
subjects_aperiodic = df_CN_aperiodic['Country_ID']
subjects_complex = df_CN_complex['t']
subjects_freq = df_CN_freq['Country_ID']

# Encontrar la intersección de los tres
common_subjects = set(subjects_aperiodic).intersection(subjects_complex).intersection(subjects_freq)

# Ver cuántos sujetos comunes existen
print(f"Número de sujetos comunes: {len(common_subjects)}")

Número de sujetos comunes: 1382

In [7]:
df_CN_aperiodic_common = df_CN_aperiodic[df_CN_aperiodic['Country_ID'].isin(common_subjects)]
df_CN_complex_common = df_CN_complex[df_CN_complex['t'].isin(common_subjects)]
df_CN_freq_common = df_CN_freq[df_CN_freq['Country_ID'].isin(common_subjects)]

# Ver las primeras filas de los DataFrames filtrados
print(df_CN_aperiodic_common.head(2))
print(df_CN_complex_common.head(2))
print(df_CN_freq_common.head(2))

   Unnamed: 0  Slope_HPC_left  Slope_HPC_right  Slope_CING_left  \
0           0        2.859768         1.767303         2.415282
1           1        1.309688         1.667206         1.528242

   Slope_CING_right  Slope_TEMP_left  Slope_TEMP_right  Slope_PARIET_left  \
0          2.727924         3.081733          2.077333           2.413411
1          1.537064         1.376505          2.009045           1.636336

   Slope_PARIET_right  Slope_OCC_left  ...  Country_x      Site_x  \
0            1.768170        3.129080  ...       Cuba  CUB_123_2_
1            1.460334        1.433874  ...       Cuba  CUB_123_2_

              Country_ID   Age  Sex  Educ  MMSE        ODQ  GINI    Site_x.1
0  CUB_123_2_sub-10001    33.0  1.0  19.0  30.0  99.282421  40.7  CUB_123_2_
1  CUB_123_2_sub-10004    57.0  2.0  13.0   NaN  99.739738  40.7  CUB_123_2_

[2 rows x 42 columns]
   Unnamed: 0  SSV_IFG_L  SSV_IFG_R  SSV_TEMP_left  SSV_TEMP_right  \
0           0   0.006332   0.005878       0.002696        0.007597
1           1   0.004393   0.006609       0.005131        0.002860

   SSV_OCC_left  SSV_OCC_right  WMEAN_ALL    PE_ALL    FD_ALL  \
0      0.001630       0.006095  -0.686534  1.115442  0.858276
1      0.008439       0.004499  -0.685793  1.107025  0.770389

  Country_Eurolad_Code Country_x                      t   Age  Sex  Educ  \
0         Cuba_123to62      Cuba  CUB_123_2_sub-10001    33.0  1.0  19.0
1         Cuba_123to62      Cuba  CUB_123_2_sub-10004    57.0  2.0  13.0

   MMSE     HDI  GINI        ODQ
0  30.0  0.7578  40.7  99.282421
1   NaN  0.7578  40.7  99.739738
   Unnamed: 0  Delta_canon_EPP_ORB_left  Delta_canon_EPP_ORB_right  \
0           0                  0.059161                   0.070466
1           1                  0.054096                   0.047097

   Delta_canon_EPP_IFG_left  Delta_canon_EPP_IFG_right  \
0                  0.051849                   0.049289
1                  0.056917                   0.044670

   Delta_canon_EPP_MFG_left  Delta_canon_EPP_MFG_right  \
0                  0.049934                   0.047389
1                  0.055201                   0.042544

   Delta_canon_EPP_SFG_left  Delta_canon_EPP_SFG_right  \
0                  0.049015                   0.047568
1                  0.048499                   0.039344

   Delta_canon_EPP_HPC_left  ...  IAF_OCC_left  IAF_OCC_right  \
0                  0.041415  ...      8.833333       8.791667
1                  0.041028  ...     11.375000      11.500000

              Country_ID   Age  Sex  Educ  MMSE     HDI  GINI        ODQ
0  CUB_123_2_sub-10001    33.0  1.0  19.0  30.0  0.7578  40.7  99.282421
1  CUB_123_2_sub-10004    57.0  2.0  13.0   NaN  0.7578  40.7  99.739738

[2 rows x 227 columns]

In [8]:
# Renombrar la columna en df_CN_complex para que coincida con los otros DataFrames
df_CN_complex_common.rename(columns={'t': 'Country_ID'}, inplace=True)

# Unir los tres DataFrames usando 'Country_ID'
df_merged_CN = df_CN_aperiodic_common.merge(df_CN_complex_common, on='Country_ID').merge(df_CN_freq_common, on='Country_ID')

# Ver el DataFrame resultante
print(df_merged_CN.head(2))

   Unnamed: 0_x  Slope_HPC_left  Slope_HPC_right  Slope_CING_left  \
0             0        2.859768         1.767303         2.415282
1             1        1.309688         1.667206         1.528242

   Slope_CING_right  Slope_TEMP_left  Slope_TEMP_right  Slope_PARIET_left  \
0          2.727924         3.081733          2.077333           2.413411
1          1.537064         1.376505          2.009045           1.636336

   Slope_PARIET_right  Slope_OCC_left  ...  IAF_INS_right  IAF_OCC_left  \
0            1.768170        3.129080  ...          8.625      8.833333
1            1.460334        1.433874  ...         11.625     11.375000

   IAF_OCC_right   Age  Sex  Educ  MMSE   HDI_y  GINI        ODQ
0       8.791667  33.0  1.0  19.0  30.0  0.7578  40.7  99.282421
1      11.500000  57.0  2.0  13.0   NaN  0.7578  40.7  99.739738

[2 rows x 287 columns]

In [11]:
df_merged_CN['ID-unique'] = range(len(df_merged_CN))

In [13]:
# Guardar el DataFrame combinado en un archivo Excel
df_merged_CN.to_excel('CN_combined.xlsx', index=False)

print("Archivo Excel guardado exitosamente.")

Archivo Excel guardado exitosamente.

# AD

In [14]:
# Directorio AD
df_AD_arg_aperiodic = pd.read_excel(f"{path_aperiodic}AD/AR_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx")
df_AD_bra_aperiodic = pd.read_excel(f"{path_aperiodic}AD/Bra_USP_AD_processed_SourceTransformation_ODQ_metrics - copia.xlsx")
df_AD_ch_aperiodic = pd.read_excel(f"{path_aperiodic}AD/CH_AD_processed_SourceTransformation_ODQ_metrics - copia.xlsx")
df_AD_col_aperiodic = pd.read_excel(f"{path_aperiodic}AD/COL_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx")
df_AD_tur_aperiodic = pd.read_excel(f"{path_aperiodic}AD/Tur_IUEFM_AD_processed_SourceTransformation_ODQ_metrics - copia.xlsx")

df_AD_arg_complex = pd.read_excel(f"{path_complex}AD/AR_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx")
df_AD_ch_complex = pd.read_excel(f"{path_complex}AD/Ch_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx")
df_AD_col_complex = pd.read_excel(f"{path_complex}AD/Col_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx")
df_AD_tur_complex = pd.read_excel(f"{path_complex}AD/Tur_AD_SourceTransformation_complex_metrics_ODQ - copia.xlsx")
df_AD_bra_complex = pd.read_excel(f"{path_complex}AD/USP_processed_SourceTransformation_AD_Complexity_metrics_ODQ.xlsx")

df_AD_arg_freq = pd.read_excel(f"{path_freq}AD/AD_ARG_freq.xlsx")
df_AD_col_freq = pd.read_excel(f"{path_freq}AD/AD_Col_freq.xlsx")
df_AD_bra_freq = pd.read_excel(f"{path_freq}AD/Bra_USP_AD_processed_SourceTransformation_ODQ_metrics.xlsx")
df_AD_ch_freq = pd.read_excel(f"{path_freq}AD/CH_freq.xlsx")
df_AD_tur_freq = pd.read_excel(f"{path_freq}AD/Tur_IUEFM_AD_processed_SourceTransformation_ODQ_metrics.xlsx")

print(df_AD_arg_aperiodic.shape, df_AD_bra_aperiodic.shape, df_AD_ch_aperiodic.shape, df_AD_col_aperiodic.shape,df_AD_tur_aperiodic.shape,
     df_AD_arg_complex.shape, df_AD_ch_complex.shape ,df_AD_col_complex.shape,df_AD_tur_complex.shape,df_AD_usp_complex.shape,
     df_AD_arg_freq.shape,df_AD_col_freq.shape,df_AD_bra_freq.shape,df_AD_ch_freq.shape,df_AD_tur_freq.shape)

(29, 42) (76, 42) (62, 42) (47, 42) (96, 42) (32, 21) (64, 22) (47, 22) (96, 22) (76, 21) (32, 231) (47, 231) (76, 231) (63, 231) (96, 231)

In [15]:
import pandas as pd
import numpy as np

# Extraer el número final de los IDs en ambos DataFrames
df_AD_arg_complex['ID_Number'] = df_AD_arg_complex['Country_ID'].str.extract(r'(\d+)$')
df_AD_arg_aperiodic['ID_Number'] = df_AD_arg_aperiodic['Country_ID'].str.extract(r'(\d+)$')
# Crear un diccionario de mapeo del segundo DataFrame
mapping = df_AD_arg_aperiodic.set_index('ID_Number')['Country_ID'].to_dict()
# Mapear los valores al primer DataFrame
df_AD_arg_complex['Country_ID_2'] = df_AD_arg_complex['ID_Number'].map(mapping)

# Eliminar la columna auxiliar si no se necesita
#df_AD_arg_complex.drop(columns='ID_Number', inplace=True)


df_AD_ch_complex['ID_Number'] = df_AD_ch_complex['Country_ID'].str.extract(r'(\d+)$')
df_AD_ch_aperiodic['ID_Number'] = df_AD_ch_aperiodic['Country_ID'].str.extract(r'(\d+)$')
mapping = df_AD_ch_aperiodic.set_index('ID_Number')['Country_ID'].to_dict()
df_AD_ch_complex['Country_ID_2'] = df_AD_ch_complex['ID_Number'].map(mapping)


df_AD_col_complex['ID_Number'] = df_AD_col_complex['Country_ID'].str.extract(r'(\d+)$')
df_AD_col_aperiodic['ID_Number'] = df_AD_col_aperiodic['Country_ID'].str.extract(r'(\d+)$')
mapping = df_AD_col_aperiodic.set_index('ID_Number')['Country_ID'].to_dict()
df_AD_col_complex['Country_ID_2'] = df_AD_col_complex['ID_Number'].map(mapping)

df_AD_ch_complex['ID_Number'] = df_AD_ch_complex['Country_ID'].str.extract(r'(\d+)$')
df_AD_ch_aperiodic['ID_Number'] = df_AD_ch_aperiodic['Country_ID'].str.extract(r'(\d+)$')
mapping = df_AD_ch_aperiodic.set_index('ID_Number')['Country_ID'].to_dict()
df_AD_ch_complex['Country_ID_2'] = df_AD_ch_complex['ID_Number'].map(mapping)


df_AD_tur_complex['ID_Number'] = df_AD_tur_complex['Country_ID'].str.extract(r'(\d+)$')
df_AD_tur_aperiodic['ID_Number'] = df_AD_tur_aperiodic['Country_ID'].str.extract(r'(\d+)$')
mapping = df_AD_tur_aperiodic.set_index('ID_Number')['Country_ID'].to_dict()
df_AD_tur_complex['Country_ID_2'] = df_AD_tur_complex['ID_Number'].map(mapping)

df_AD_bra_complex['ID_Number'] = df_AD_bra_complex['Country_ID'].str.extract(r'(\d+)$')
df_AD_bra_aperiodic['ID_Number'] = df_AD_bra_aperiodic['Country_ID'].str.extract(r'(\d+)$')
mapping = df_AD_bra_aperiodic.set_index('ID_Number')['Country_ID'].to_dict()
df_AD_bra_complex['Country_ID_2'] = df_AD_bra_complex['ID_Number'].map(mapping)


# Ver el resultado
#print(df_AD_arg_complex)

In [16]:
import pandas as pd

# Concatenamos todos los DataFrames en cada lista
df_AD_aperiodic = pd.concat([df_AD_arg_aperiodic, df_AD_bra_aperiodic, df_AD_ch_aperiodic, df_AD_col_aperiodic, df_AD_tur_aperiodic], ignore_index=True)
df_AD_complex = pd.concat([df_AD_arg_complex, df_AD_bra_complex, df_AD_ch_complex, df_AD_col_complex, df_AD_tur_complex], ignore_index=True)
df_AD_freq = pd.concat([df_AD_arg_freq,  df_AD_bra_freq, df_AD_ch_freq,df_AD_col_freq, df_AD_tur_freq], ignore_index=True)

In [17]:
df_AD_aperiodic['Country_ID_2']=df_AD_aperiodic['Country_ID']
df_AD_freq['Country_ID_2']=df_AD_freq['Country_ID']

In [18]:
# Extraemos las listas de identificadores de cada DataFrame
subjects_aperiodic = df_AD_aperiodic['Country_ID_2']
subjects_complex = df_AD_complex['Country_ID_2']
subjects_freq = df_AD_freq['Country_ID']

In [ ]:
# Encontrar la intersección de los tres
common_subjects = set(subjects_aperiodic).intersection(subjects_complex).intersection(subjects_freq)

# Ver cuántos sujetos comunes existen
print(f"Número de sujetos comunes: {len(common_subjects)}")

Número de sujetos comunes: 306

In [20]:
df_AD_aperiodic_common = df_AD_aperiodic[df_AD_aperiodic['Country_ID_2'].isin(common_subjects)]
df_AD_complex_common = df_AD_complex[df_AD_complex['Country_ID_2'].isin(common_subjects)]
df_AD_freq_common = df_AD_freq[df_AD_freq['Country_ID_2'].isin(common_subjects)]

# Ver las primeras filas de los DataFrames filtrados
print(df_AD_aperiodic_common.head(2))
print(df_AD_complex_common.head(2))
print(df_AD_freq_common.head(2))

  Unnamed: 0  Slope_HPC_left  Slope_HPC_right  Slope_CING_left  \
4          4        1.657409         1.791276         3.266917
5          5        1.948224         2.565999         1.030199

   Slope_CING_right  Slope_TEMP_left  Slope_TEMP_right  Slope_PARIET_left  \
4          3.692153         2.078647          1.445966           1.445989
5          1.142947         1.527375          1.753363           1.041908

   Slope_PARIET_right  Slope_OCC_left  ...  Educ   MMSE        ODQ    Country  \
4            2.056778        1.040193  ...     6  23.74  99.524933  Argentina
5            1.093190        1.087747  ...     6  22.62  99.673196  Argentina

   Eurolad_code  GINI  Group         ID  ID_Number       Country_ID_2
4       ARG_F14  41.8     AD  sub-10007      10007  ARG_F14_sub-10007
5       ARG_F14  41.8     AD  sub-10008      10008  ARG_F14_sub-10008

[2 rows x 44 columns]
   Unnamed: 0  SSV_IFG_L  SSV_IFG_R  SSV_TEMP_left  SSV_TEMP_right  \
0           0   0.011544   0.030967       0.018491        0.020651
1           1   0.013147   0.016928       0.009042        0.013326

   SSV_OCC_left  SSV_OCC_right  WMEAN_ALL    PE_ALL    FD_ALL  ...   MMSE  \
0      0.030779       0.030360  -0.724314  1.236883  1.158058  ...  24.22
1      0.014114       0.012831  -0.704504  1.203216  1.092852  ...  22.78

         ODQ    Country                          Eurolad_code  GINI  Group  \
0  98.826428  Argentina  EUROLAD_BRAINLAT_RS_Batch1_Argentina  41.8     AD
1  99.458111  Argentina  EUROLAD_BRAINLAT_RS_Batch1_Argentina  41.8     AD

          ID ID_Number              Country_ID_2 Diagnosis
0  sub-10002     10002  ARG_Tak_Martin_sub-10002       NaN
1  sub-10003     10003  ARG_Tak_Martin_sub-10003       NaN

[2 rows x 24 columns]
   Unnamed: 0  Delta_canon_EPP_ORB_left  Delta_canon_EPP_ORB_right  \
4           4                  0.039235                   0.049057
5           5                  0.036242                   0.041390

   Delta_canon_EPP_IFG_left  Delta_canon_EPP_IFG_right  \
4                  0.038911                   0.046644
5                  0.033360                   0.036910

   Delta_canon_EPP_MFG_left  Delta_canon_EPP_MFG_right  \
4                  0.030848                   0.034442
5                  0.034044                   0.032945

   Delta_canon_EPP_SFG_left  Delta_canon_EPP_SFG_right  \
4                  0.039729                   0.046127
5                  0.036357                   0.038432

   Delta_canon_EPP_HPC_left  ...  Educ   MMSE        ODQ    Country  \
4                  0.038986  ...   6.0  23.74  99.524933  Argentina
5                  0.035900  ...   6.0  22.62  99.673196  Argentina

   Eurolad_code  GINI  Group         ID  Diagnosis       Country_ID_2
4       ARG_F14  41.8     AD  sub-10007          1  ARG_F14_sub-10007
5       ARG_F14  41.8     AD  sub-10008          1  ARG_F14_sub-10008

[2 rows x 232 columns]

In [21]:
# Renombrar la columna en df_CN_complex para que coincida con los otros DataFrames
#df_AD_complex_common.rename(columns={'t': 'Country_ID'}, inplace=True)

# Unir los tres DataFrames usando 'Country_ID'
df_merged_AD = df_AD_aperiodic_common.merge(df_AD_complex_common, on='Country_ID_2').merge(df_AD_freq_common, on='Country_ID_2')

# Ver el DataFrame resultante
print(df_merged_AD.head(2))

  Unnamed: 0_x  Slope_HPC_left  Slope_HPC_right  Slope_CING_left  \
0            4        1.657409         1.791276         3.266917
1            5        1.948224         2.565999         1.030199

   Slope_CING_right  Slope_TEMP_left  Slope_TEMP_right  Slope_PARIET_left  \
0          3.692153         2.078647          1.445966           1.445989
1          1.142947         1.527375          1.753363           1.041908

   Slope_PARIET_right  Slope_OCC_left  ...   Age  Educ   MMSE        ODQ  \
0            2.056778        1.040193  ...  71.0   6.0  23.74  99.524933
1            1.093190        1.087747  ...  80.0   6.0  22.62  99.673196

     Country  Eurolad_code  GINI  Group         ID  Diagnosis_y
0  Argentina       ARG_F14  41.8     AD  sub-10007            1
1  Argentina       ARG_F14  41.8     AD  sub-10008            1

[2 rows x 298 columns]

In [22]:
df_merged_AD['ID-unique'] = range(len(df_merged_AD))

In [23]:
# Guardar el DataFrame combinado en un archivo Excel
df_merged_AD.to_excel('AD_combined.xlsx', index=False)

print("Archivo Excel guardado exitosamente.")

Archivo Excel guardado exitosamente.

# FTD

In [71]:
# Directorio FTD
df_FTD_arg_aperiodic = pd.read_excel(f"{path_aperiodic}FTD/ARG_FTD_processed_SourceTransformation_ODQ_metrics - copia.xlsx")
df_FTD_ch_aperiodic = pd.read_excel(f"{path_aperiodic}FTD/CH_FTD_processed_SourceTransformation_ODQ_metrics - copia.xlsx")
df_FTD_col_aperiodic = pd.read_excel(f"{path_aperiodic}FTD/Col_processed_SourceTransformation_ODQ_metrics - copia.xlsx")

# Directorio FTD
df_FTD_arg_complex = pd.read_excel(f"{path_complex}FTD/ARG_processed_SourceTransformation_FTD_ODQ_metrics - copia.xlsx")
df_FTD_ch_complex = pd.read_excel(f"{path_complex}FTD/CH_processed_SourceTransformation_FTD_ODQ_metrics - copia.xlsx")
df_FTD_col_complex = pd.read_excel(f"{path_complex}FTD/Col_processed_SourceTransformation_FTD_ODQ_metrics - copia.xlsx")

df_FTD_arg_freq = pd.read_excel(f"{path_freq}FTD/ARG_FTD_freq.xlsx")
df_FTD_ch_freq = pd.read_excel(f"{path_freq}FTD/CH_FTD_freq.xlsx")
df_FTD_col_freq = pd.read_excel(f"{path_freq}FTD/Tak_Col_Bog_processed_SourceTransformation_ODQ_metrics.xlsx")


print(df_FTD_arg_aperiodic.shape, df_FTD_ch_aperiodic.shape, df_FTD_col_aperiodic.shape,
     df_FTD_arg_complex.shape, df_FTD_ch_complex.shape ,df_FTD_col_complex.shape,
     df_FTD_arg_freq.shape,df_FTD_ch_freq.shape,df_FTD_col_freq.shape)

(29, 39) (24, 39) (12, 40) (31, 21) (24, 21) (12, 21) (32, 231) (24, 231) (6, 231)

In [72]:
# Seleccionar las columnas relevantes para la comparación
columns_to_match = ['Age', 'Sex', 'Educ', 'MMSE', 'ODQ', 'GINI']

# Realizar un merge con las columnas clave para encontrar coincidencias
merged_df = df_FTD_arg_aperiodic.merge(
    df_FTD_arg_complex[['ID'] + columns_to_match], 
    on=columns_to_match, 
    how='left'
)

# Verificar el resultado
df_FTD_arg_aperiodic['ID'] = merged_df['ID']

# Imprimir los primeros registros para confirmar
print(df_FTD_arg_aperiodic.head())

   Unnamed: 0  Slope_HPC_left  Slope_HPC_right  Slope_CING_left  \
0           0        1.155978         1.660777         2.298852
1           1        1.479669         1.437262         1.396243
2           2        1.376364         0.875103         1.092503
3           3        0.636676         0.784739         0.660823
4           4        2.089692         1.522240         3.517030

   Slope_CING_right  Slope_TEMP_left  Slope_TEMP_right  Slope_PARIET_left  \
0          2.571176         1.868578          2.245640           2.193582
1          1.469099         1.514617          1.306546           1.439433
2          1.423893         1.297217          0.857772           0.883458
3          0.687036         0.556988          0.735036           0.629617
4          4.265048         2.231430          1.181279           2.116937

   Slope_PARIET_right  Slope_OCC_left  ...  Offset_OCC_right   Age  Sex  Educ  \
0            2.285243        0.895963  ...          2.446361  78.0    2  16.0
1            1.493425        1.684383  ...          3.058808   NaN    2   NaN
2            0.832648        1.176525  ...          1.680833  67.0    2  15.0
3            0.809984        0.809916  ...          1.818057  79.0    2  18.0
4            3.467669        2.082405  ...          3.503956  67.0    1  17.0

    MMSE        ODQ   GINI  Diagnosis  Region         ID
0  26.94  99.487845  41.40        FTD     ARG  sub-10001
1  13.34  99.278556  41.40        FTD     ARG  sub-10002
2  25.98  99.378170  41.74        FTD     ARG  sub-10003
3  28.38  99.244345  41.40        FTD     ARG  sub-10004
4  27.10  99.728326  41.40        FTD     ARG  sub-10006

[5 rows x 40 columns]

In [73]:
# Seleccionar las columnas relevantes para la comparación
columns_to_match = ['Age', 'Sex', 'Educ', 'MMSE', 'ODQ', 'GINI']

# Realizar un merge con las columnas clave para encontrar coincidencias
merged_df = df_FTD_ch_aperiodic.merge(
    df_FTD_ch_complex[['ID'] + columns_to_match], 
    on=columns_to_match, 
    how='left'
)

# Verificar el resultado
df_FTD_ch_aperiodic['ID'] = merged_df['ID']

# Imprimir los primeros registros para confirmar
print(df_FTD_ch_aperiodic.head())

   Unnamed: 0  Slope_HPC_left  Slope_HPC_right  Slope_CING_left  \
0           0        1.152444         1.451740         1.708557
1           1        1.429064         1.330094         1.921705
2           2        2.107656         3.100740         4.347946
3           3        1.691928         2.150653         2.639260
4           4        1.819893         1.193556         1.802277

   Slope_CING_right  Slope_TEMP_left  Slope_TEMP_right  Slope_PARIET_left  \
0          2.004557         1.257764          1.227816           1.797962
1          2.128663         1.139679          0.789181           2.338547
2          4.808743         2.117354          3.343650           3.770900
3          2.585239         1.858526          2.121278           2.458118
4          1.945397         1.299366          1.142186           2.042477

   Slope_PARIET_right  Slope_OCC_left  ...  Offset_OCC_right  Age  Sex  Educ  \
0            1.743610        0.801429  ...          2.358646   59    1   8.0
1            2.530538        1.816535  ...          4.062005   56    1  18.0
2            4.846827        2.484834  ...          8.069997   72    2  18.0
3            2.234587        1.764619  ...          4.254008   82    1  20.0
4            2.115083        2.309566  ...          4.545589   59    2  18.0

    MMSE        ODQ  GINI  Diagnosis  Region         ID
0  25.22  99.673526  45.3          1      CH  sub-20002
1  26.80  99.198425  45.3          1      CH  sub-20004
2  29.96  99.782774  45.3          1      CH  sub-20005
3  29.17  99.527439  45.3          1      CH  sub-20007
4  25.22  99.692581  45.3          1      CH  sub-20008

[5 rows x 40 columns]

In [74]:
# Eliminar la columna 'ID'
df_FTD_col_aperiodic = df_FTD_col_aperiodic.drop(columns=['ID'])

# Confirmar que la columna fue eliminada
print(df_FTD_col_aperiodic.head())

   Unnamed: 0  Slope_HPC_left  Slope_HPC_right  Slope_CING_left  \
0           0        0.424469         0.288465         0.607284
1           1        1.140681         1.369872         2.348509
2           2        2.524440         2.846771         3.709630
3           3        0.578102         0.593318         2.021242
4           4        1.302915         0.779208         2.254821

   Slope_CING_right  Slope_TEMP_left  Slope_TEMP_right  Slope_PARIET_left  \
0          0.695146         0.196421          0.196778           0.513886
1          2.509321         1.197316          1.081712           2.385420
2          3.695838         2.604534          2.676552           3.634983
3          2.025784         0.680070          0.620585           1.392379
4          2.243423         0.968474          0.346802           1.644460

   Slope_PARIET_right  Slope_OCC_left  ...  Offset_OCC_left  Offset_OCC_right  \
0            0.839645        0.258914  ...         1.024726         -1.708962
1            2.596747        1.199884  ...         2.383952          2.802160
2            3.650585        2.983779  ...         3.984644          5.027055
3            1.352642        1.301744  ...         1.999183          1.930320
4            1.914440        2.007854  ...         2.820300          2.582438

   Age  Sex  Educ  MMSE        ODQ  GINI  Diagnosis  Region
0   64    2     2  22.0  80.121513  55.1          1     Col
1   72    1     8  16.0  94.288472  55.1          1     Col
2   75    1    16  29.0  99.366117  55.1          1     Col
3   63    1     4  18.0  95.111716  55.1          1     Col
4   65    2     1  21.0  94.287741  55.1          1     Col

[5 rows x 39 columns]

In [75]:
# Seleccionar las columnas relevantes para la comparación
columns_to_match = ['Age', 'Sex', 'Educ',  'ODQ']

# Realizar un merge con las columnas clave para encontrar coincidencias
merged_df = df_FTD_col_aperiodic.merge(
    df_FTD_col_complex[['ID'] + columns_to_match], 
    on=columns_to_match, 
    how='left'
)

# Verificar el resultado
df_FTD_col_aperiodic['ID'] = merged_df['ID']

# Imprimir los primeros registros para confirmar
print(df_FTD_col_aperiodic.head())

   Unnamed: 0  Slope_HPC_left  Slope_HPC_right  Slope_CING_left  \
0           0        0.424469         0.288465         0.607284
1           1        1.140681         1.369872         2.348509
2           2        2.524440         2.846771         3.709630
3           3        0.578102         0.593318         2.021242
4           4        1.302915         0.779208         2.254821

   Slope_CING_right  Slope_TEMP_left  Slope_TEMP_right  Slope_PARIET_left  \
0          0.695146         0.196421          0.196778           0.513886
1          2.509321         1.197316          1.081712           2.385420
2          3.695838         2.604534          2.676552           3.634983
3          2.025784         0.680070          0.620585           1.392379
4          2.243423         0.968474          0.346802           1.644460

   Slope_PARIET_right  Slope_OCC_left  ...  Offset_OCC_right  Age  Sex  Educ  \
0            0.839645        0.258914  ...         -1.708962   64    2     2
1            2.596747        1.199884  ...          2.802160   72    1     8
2            3.650585        2.983779  ...          5.027055   75    1    16
3            1.352642        1.301744  ...          1.930320   63    1     4
4            1.914440        2.007854  ...          2.582438   65    2     1

   MMSE        ODQ  GINI  Diagnosis  Region         ID
0  22.0  80.121513  55.1          1     Col  sub-30001
1  16.0  94.288472  55.1          1     Col  sub-30002
2  29.0  99.366117  55.1          1     Col  sub-30003
3  18.0  95.111716  55.1          1     Col  sub-30004
4  21.0  94.287741  55.1          1     Col  sub-30005

[5 rows x 40 columns]

In [76]:
import pandas as pd
import numpy as np

# Extraer el número final de los IDs en ambos DataFrames
df_FTD_arg_complex['ID_Number'] = df_FTD_arg_complex['ID'].str.extract(r'(\d+)$')
df_FTD_arg_aperiodic['ID_Number'] = df_FTD_arg_aperiodic['ID'].str.extract(r'(\d+)$')
# Crear un diccionario de mapeo del segundo DataFrame
mapping = df_FTD_arg_aperiodic.set_index('ID_Number')['ID'].to_dict()
# Mapear los valores al primer DataFrame
df_FTD_arg_complex['Country_ID_2'] = df_FTD_arg_complex['ID_Number'].map(mapping)

# Eliminar la columna auxiliar si no se necesita
#df_AD_arg_complex.drop(columns='ID_Number', inplace=True)


df_FTD_ch_complex['ID_Number'] = df_FTD_ch_complex['ID'].str.extract(r'(\d+)$')
df_FTD_ch_aperiodic['ID_Number'] = df_FTD_ch_aperiodic['ID'].str.extract(r'(\d+)$')
mapping = df_FTD_ch_aperiodic.set_index('ID_Number')['ID'].to_dict()
df_FTD_ch_complex['Country_ID_2'] = df_FTD_ch_complex['ID_Number'].map(mapping)


df_FTD_col_complex['ID_Number'] = df_FTD_col_complex['ID'].str.extract(r'(\d+)$')
df_FTD_col_aperiodic['ID_Number'] = df_FTD_col_aperiodic['ID'].str.extract(r'(\d+)$')
mapping = df_FTD_col_aperiodic.set_index('ID_Number')['ID'].to_dict()
df_FTD_col_complex['Country_ID_2'] = df_FTD_col_complex['ID_Number'].map(mapping)

In [78]:
import pandas as pd

# Concatenamos todos los DataFrames en cada lista
df_FTD_aperiodic = pd.concat([df_FTD_arg_aperiodic,  df_FTD_ch_aperiodic, df_FTD_col_aperiodic], ignore_index=True)
df_FTD_complex = pd.concat([df_FTD_arg_complex,  df_FTD_ch_complex, df_FTD_col_complex], ignore_index=True)
df_FTD_freq = pd.concat([df_FTD_arg_freq,   df_FTD_ch_freq, df_FTD_col_freq], ignore_index=True)

In [80]:
df_FTD_aperiodic['Country_ID_2']=df_AD_aperiodic['ID']
df_FTD_freq['Country_ID_2']=df_AD_freq['ID']

In [81]:
# Extraemos las listas de identificadores de cada DataFrame
subjects_aperiodic = df_FTD_aperiodic['Country_ID_2']
subjects_complex = df_FTD_complex['Country_ID_2']
subjects_freq = df_FTD_freq['Country_ID_2']

In [82]:
# Encontrar la intersección de los tres
common_subjects = set(subjects_aperiodic).intersection(subjects_complex).intersection(subjects_freq)

# Ver cuántos sujetos comunes existen
print(f"Número de sujetos comunes: {len(common_subjects)}")

Número de sujetos comunes: 53

In [83]:
df_FTD_aperiodic_common = df_FTD_aperiodic[df_FTD_aperiodic['Country_ID_2'].isin(common_subjects)]
df_FTD_complex_common = df_FTD_complex[df_FTD_complex['Country_ID_2'].isin(common_subjects)]
df_FTD_freq_common = df_FTD_freq[df_FTD_freq['Country_ID_2'].isin(common_subjects)]

# Ver las primeras filas de los DataFrames filtrados
print(df_FTD_aperiodic_common.head(2))
print(df_FTD_complex_common.head(2))
print(df_FTD_freq_common.head(2))

   Unnamed: 0  Slope_HPC_left  Slope_HPC_right  Slope_CING_left  \
0           0        1.155978         1.660777         2.298852
1           1        1.479669         1.437262         1.396243

   Slope_CING_right  Slope_TEMP_left  Slope_TEMP_right  Slope_PARIET_left  \
0          2.571176         1.868578          2.245640           2.193582
1          1.469099         1.514617          1.306546           1.439433

   Slope_PARIET_right  Slope_OCC_left  ...  Sex  Educ   MMSE        ODQ  GINI  \
0            2.285243        0.895963  ...    2  16.0  26.94  99.487845  41.4
1            1.493425        1.684383  ...    2   NaN  13.34  99.278556  41.4

   Diagnosis  Region         ID  ID_Number  Country_ID_2
0        FTD     ARG  sub-10001      10001     sub-10001
1        FTD     ARG  sub-10002      10002     sub-10002

[2 rows x 42 columns]
   Unnamed: 0  SSV_IFG_L  SSV_IFG_R  SSV_TEMP_left  SSV_TEMP_right  \
0           0   0.010600   0.009268       0.013137        0.015041
1           1   0.030561   0.036426       0.028332        0.026413

   SSV_OCC_left  SSV_OCC_right  WMEAN_ALL    PE_ALL    FD_ALL  ...  Educ  \
0      0.033191       0.023228   -0.71508  1.229162  1.205439  ...  16.0
1      0.022682       0.020104   -0.73336  1.282262  1.288468  ...   NaN

    MMSE        ODQ    Country  Eurolad_code  GINI Group         ID  \
0  26.94  99.487845  Argentina       ARG_F14  41.4   FTD  sub-10001
1  13.34  99.278556  Argentina       ARG_F14  41.4   FTD  sub-10002

   ID_Number Country_ID_2
0      10001    sub-10001
1      10002    sub-10002

[2 rows x 23 columns]
   Unnamed: 0  Delta_canon_EPP_ORB_left  Delta_canon_EPP_ORB_right  \
0           0                  0.046469                   0.050542
1           1                  0.039010                   0.042470

   Delta_canon_EPP_IFG_left  Delta_canon_EPP_IFG_right  \
0                  0.043767                   0.052175
1                  0.037282                   0.039936

   Delta_canon_EPP_MFG_left  Delta_canon_EPP_MFG_right  \
0                  0.037762                   0.039713
1                  0.033279                   0.030438

   Delta_canon_EPP_SFG_left  Delta_canon_EPP_SFG_right  \
0                  0.039118                   0.048774
1                  0.039252                   0.041048

   Delta_canon_EPP_HPC_left  ...  Educ   MMSE        ODQ    Country  \
0                  0.034475  ...  16.0  26.94  99.487845  Argentina
1                  0.077929  ...   NaN  13.34  99.278556  Argentina

   Eurolad_code  GINI  Group         ID  Diagnosis  Country_ID_2
0       ARG_F14  41.4    FTD  sub-10001          1     sub-10001
1       ARG_F14  41.4    FTD  sub-10002          1     sub-10002

[2 rows x 232 columns]

In [84]:
# Renombrar la columna en df_CN_complex para que coincida con los otros DataFrames
#df_AD_complex_common.rename(columns={'t': 'Country_ID'}, inplace=True)

# Unir los tres DataFrames usando 'Country_ID'
df_merged_FTD = df_FTD_aperiodic_common.merge(df_FTD_complex_common, on='Country_ID_2').merge(df_FTD_freq_common, on='Country_ID_2')

# Ver el DataFrame resultante
print(df_merged_FTD.head(2))

   Unnamed: 0_x  Slope_HPC_left  Slope_HPC_right  Slope_CING_left  \
0             0        1.155978         1.660777         2.298852
1             1        1.479669         1.437262         1.396243

   Slope_CING_right  Slope_TEMP_left  Slope_TEMP_right  Slope_PARIET_left  \
0          2.571176         1.868578          2.245640           2.193582
1          1.469099         1.514617          1.306546           1.439433

   Slope_PARIET_right  Slope_OCC_left  ...   Age  Educ   MMSE        ODQ  \
0            2.285243        0.895963  ...  78.0  16.0  26.94  99.487845
1            1.493425        1.684383  ...   NaN   NaN  13.34  99.278556

   Country_y  Eurolad_code_y  GINI  Group_y         ID  Diagnosis_y
0  Argentina         ARG_F14  41.4      FTD  sub-10001            1
1  Argentina         ARG_F14  41.4      FTD  sub-10002            1

[2 rows x 295 columns]

In [85]:
df_merged_FTD['ID-unique'] = range(len(df_merged_FTD))

In [86]:
# Guardar el DataFrame combinado en un archivo Excel
df_merged_FTD.to_excel('FTD_combined.xlsx', index=False)

print("Archivo Excel guardado exitosamente.")

Archivo Excel guardado exitosamente.

# MCI

In [10]:
# Directorio MCI
df_MCI_col_aperiodic = pd.read_excel(f"{path_aperiodic}MCI/Col_MCI_processed_SourceTransformation_ODQ_metrics.xlsx")
df_MCI_tur_aperiodic = pd.read_excel(f"{path_aperiodic}MCI/Tur_IUEFM_MCI_processed_SourceTransformation_ODQ_metrics.xlsx")

df_MCI_col_complex = pd.read_excel(f"{path_complex}MCI/Col_USCO_processed_SourceTransformation_MCI_ODQ_metrics - copia.xlsx")
df_MCI_tur_complex = pd.read_excel(f"{path_complex}MCI/Tur_IUEFM_processed_SourceTransformation_DCL_ODQ_metrics - copia.xlsx")

df_MCI_col_freq = pd.read_excel(f"{path_freq}MCI/Col_MCI_processed_SourceTransformation_ODQ_metrics.xlsx")
df_MCI_tur_freq = pd.read_excel(f"{path_freq}MCI/Tur_IUEFM_MCI_processed_SourceTransformation_ODQ_metrics.xlsx")

print(df_MCI_col_aperiodic.shape, df_MCI_tur_aperiodic.shape,
     df_MCI_col_complex.shape, df_MCI_tur_complex.shape ,
     df_MCI_col_freq.shape,df_MCI_tur_freq.shape)

(133, 42) (95, 42) (133, 21) (95, 21) (133, 231) (95, 231)

In [ ]:
df_MCI_col_aperiodic

In [ ]:
df_MCI_col_complex

In [ ]:
df_MCI_col_freq

In [15]:
import pandas as pd

# Concatenamos todos los DataFrames en cada lista
df_MCI_aperiodic = pd.concat([df_MCI_col_aperiodic, df_MCI_tur_aperiodic], ignore_index=True)
df_MCI_complex = pd.concat([df_MCI_col_complex, df_MCI_tur_complex], ignore_index=True)
df_MCI_freq = pd.concat([df_MCI_col_freq,  df_MCI_tur_freq], ignore_index=True)

In [19]:
df_MCI_aperiodic['Group']='MCI'

In [22]:
df_MCI_freq['Group']='MCI'

In [23]:
df_MCI_aperiodic

,Unnamed: 0,Slope_HPC_left,Slope_HPC_right,Slope_CING_left,Slope_CING_right,Slope_TEMP_left,Slope_TEMP_right,Slope_PARIET_left,Slope_PARIET_right,Slope_OCC_left,...,Sex,Age,Educ,MMSE,ODQ,Country,Eurolad_code,GINI,Group,ID
0,0,1.337510,2.251347,1.233506,1.504801,1.379055,1.559732,1.618886,1.483839,1.327416,...,2,59,12,27.0,99.469512,Colombia,Col_USCO,54.800000,MCI,sub-10003
1,1,0.915137,0.630239,0.791544,1.057216,0.682451,0.459493,1.223334,1.238947,0.782806,...,1,65,16,22.0,98.257927,Colombia,Col_USCO,54.800000,MCI,sub-10004
2,2,0.946000,0.888339,1.427817,1.247380,1.002504,0.753283,1.083692,1.115191,0.917943,...,1,62,10,29.0,93.460366,Colombia,Col_USCO,54.800000,MCI,sub-10005
3,3,1.517780,1.564565,2.433183,2.354915,1.650920,1.598220,2.099007,1.940144,1.789507,...,2,62,5,29.0,99.642073,Colombia,Col_USCO,54.800000,MCI,sub-100011
4,4,0.543274,0.362486,0.775562,0.767149,0.475607,0.329914,0.986994,1.140920,0.864202,...,2,60,13,29.0,99.218902,Colombia,Col_USCO,54.800000,MCI,sub-100012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,90,0.928654,1.856354,2.726174,2.762248,1.267515,1.718738,2.487732,3.031800,2.651434,...,2,72,15,30.0,98.339968,Turquia,Tur_IUEFM,43.329412,MCI,sub-100091
224,91,0.803074,1.787699,1.607293,1.930484,1.469562,1.155832,1.485975,1.639788,2.170839,...,2,71,15,28.0,99.061914,Turquia,Tur_IUEFM,43.329412,MCI,sub-100092
225,92,1.460791,1.294854,1.542707,1.517642,1.397412,1.454550,1.477974,1.856550,1.355568,...,1,85,15,30.0,98.350109,Turquia,Tur_IUEFM,43.329412,MCI,sub-100093
226,93,1.997895,1.862788,3.159962,3.144280,1.928190,1.800237,3.071476,3.190662,1.727437,...,1,71,11,25.0,99.612722,Turquia,Tur_IUEFM,43.329412,MCI,sub-100094
227,94,1.436777,1.098632,2.590858,2.446654,1.025523,1.089471,1.505783,2.339749,2.932519,...,2,74,11,26.0,99.530323,Turquia,Tur_IUEFM,43.329412,MCI,sub-100095

In [24]:
# Extraemos las listas de identificadores de cada DataFrame
subjects_aperiodic = df_MCI_aperiodic['ID']
subjects_complex = df_MCI_complex['ID']
subjects_freq = df_MCI_freq['ID']

In [25]:
# Encontrar la intersección de los tres
common_subjects = set(subjects_aperiodic).intersection(subjects_complex).intersection(subjects_freq)

# Ver cuántos sujetos comunes existen
print(f"Número de sujetos comunes: {len(common_subjects)}")

Número de sujetos comunes: 186

In [26]:
df_MCI_aperiodic_common = df_MCI_aperiodic[df_MCI_aperiodic['ID'].isin(common_subjects)]
df_MCI_complex_common = df_MCI_complex[df_MCI_complex['ID'].isin(common_subjects)]
df_MCI_freq_common = df_MCI_freq[df_MCI_freq['ID'].isin(common_subjects)]

# Ver las primeras filas de los DataFrames filtrados
print(df_MCI_aperiodic_common.head(2))
print(df_MCI_complex_common.head(2))
print(df_MCI_freq_common.head(2))

   Unnamed: 0  Slope_HPC_left  Slope_HPC_right  Slope_CING_left  \
0           0        1.337510         2.251347         1.233506
1           1        0.915137         0.630239         0.791544

   Slope_CING_right  Slope_TEMP_left  Slope_TEMP_right  Slope_PARIET_left  \
0          1.504801         1.379055          1.559732           1.618886
1          1.057216         0.682451          0.459493           1.223334

   Slope_PARIET_right  Slope_OCC_left  ...  Sex  Age  Educ  MMSE        ODQ  \
0            1.483839        1.327416  ...    2   59    12  27.0  99.469512
1            1.238947        0.782806  ...    1   65    16  22.0  98.257927

    Country  Eurolad_code  GINI  Group         ID
0  Colombia      Col_USCO  54.8    MCI  sub-10003
1  Colombia      Col_USCO  54.8    MCI  sub-10004

[2 rows x 42 columns]
   Unnamed: 0  SSV_IFG_L  SSV_IFG_R  SSV_TEMP_left  SSV_TEMP_right  \
0           0   0.046506   0.040475       0.041438        0.034626
1           1   0.061898   0.062029       0.035868        0.042345

   SSV_OCC_left  SSV_OCC_right  WMEAN_ALL    PE_ALL    FD_ALL  ... Sex  Age  \
0      0.021218       0.018099  -0.751964  1.307162  1.376929  ...   2   59
1      0.028599       0.025232  -0.767999  1.336364  1.384304  ...   1   65

   Educ  MMSE        ODQ   Country   Eurolad_code  GINI  Group         ID
0    12  27.0  99.469512  Colombia  Colombia_USCO  54.8    MCI  sub-10003
1    16  22.0  98.257927  Colombia  Colombia_USCO  54.8    MCI  sub-10004

[2 rows x 21 columns]
   Unnamed: 0  Delta_canon_EPP_ORB_left  Delta_canon_EPP_ORB_right  \
0           0                  0.027003                   0.029287
1           1                  0.033561                   0.030967

   Delta_canon_EPP_IFG_left  Delta_canon_EPP_IFG_right  \
0                  0.025930                   0.028103
1                  0.030743                   0.031499

   Delta_canon_EPP_MFG_left  Delta_canon_EPP_MFG_right  \
0                  0.026956                   0.025955
1                  0.029547                   0.029677

   Delta_canon_EPP_SFG_left  Delta_canon_EPP_SFG_right  \
0                  0.029690                   0.030135
1                  0.031265                   0.032300

   Delta_canon_EPP_HPC_left  ...  Age  Educ  MMSE        ODQ   Country  \
0                  0.028117  ...   59  12.0  27.0  99.469512  Colombia
1                  0.030579  ...   65  16.0  22.0  98.257927  Colombia

   Eurolad_code  GINI  Group         ID  Diagnosis
0      Col_USCO  54.8    MCI  sub-10003          1
1      Col_USCO  54.8    MCI  sub-10004          1

[2 rows x 231 columns]

In [27]:
# Renombrar la columna en df_CN_complex para que coincida con los otros DataFrames
#df_AD_complex_common.rename(columns={'t': 'Country_ID'}, inplace=True)

# Unir los tres DataFrames usando 'Country_ID'
df_merged_MCI = df_MCI_aperiodic_common.merge(df_MCI_complex_common, on='ID').merge(df_MCI_freq_common, on='ID')

# Ver el DataFrame resultante
print(df_merged_MCI.head(2))

   Unnamed: 0_x  Slope_HPC_left  Slope_HPC_right  Slope_CING_left  \
0             0         1.33751         2.251347         1.233506
1             0         1.33751         2.251347         1.233506

   Slope_CING_right  Slope_TEMP_left  Slope_TEMP_right  Slope_PARIET_left  \
0          1.504801         1.379055          1.559732           1.618886
1          1.504801         1.379055          1.559732           1.618886

   Slope_PARIET_right  Slope_OCC_left  ...  Sex  Age  Educ  MMSE        ODQ  \
0            1.483839        1.327416  ...    2   59  12.0  27.0  99.469512
1            1.483839        1.327416  ...    1   59   5.0  23.0  99.723011

    Country  Eurolad_code       GINI  Group  Diagnosis
0  Colombia      Col_USCO  54.800000    MCI          1
1   Turquia     Tur_IUEFM  43.329412    MCI          1

[2 rows x 292 columns]

In [28]:
df_merged_MCI['ID-unique'] = range(len(df_merged_MCI))

In [29]:
# Guardar el DataFrame combinado en un archivo Excel
df_merged_MCI.to_excel('MCI_combined.xlsx', index=False)

print("Archivo Excel guardado exitosamente.")

Archivo Excel guardado exitosamente.

# Revision data

In [32]:
path_metric = 'C:/Users/felipe/OneDrive - Universidad Técnica Federico Santa María/Documentos/Brain/Multiple_Brain_Age_Clocks/pre_data'

In [36]:
df_CN_ = pd.read_excel(f"{path_metric}/CN_combined.xlsx")
df_AD_ = pd.read_excel(f"{path_metric}/AD_combined.xlsx")
df_FTD_ = pd.read_excel(f"{path_metric}/FTD_combined.xlsx")
df_MCI_ = pd.read_excel(f"{path_metric}/MCI_combined.xlsx")

In [37]:
df_CN_.head()

,Unnamed: 0_x,Slope_HPC_left,Slope_HPC_right,Slope_CING_left,Slope_CING_right,Slope_TEMP_left,Slope_TEMP_right,Slope_PARIET_left,Slope_PARIET_right,Slope_OCC_left,...,IAF_OCC_left,IAF_OCC_right,Age,Sex,Educ,MMSE,HDI_y,GINI,ODQ,ID-unique
0,0,2.859768,1.767303,2.415282,2.727924,3.081733,2.077333,2.413411,1.768170,3.129080,...,8.833333,8.791667,33.0,1.0,19.0,30.0,0.7578,40.7,99.282421,0
1,1,1.309688,1.667206,1.528242,1.537064,1.376505,2.009045,1.636336,1.460334,1.433874,...,11.375000,11.500000,57.0,2.0,13.0,NaN,0.7578,40.7,99.739738,1
2,2,1.257444,0.840704,1.330353,1.294367,1.342255,0.898285,1.438093,1.368015,1.307053,...,10.125000,10.166667,32.0,1.0,10.0,NaN,0.7578,40.7,99.361739,2
3,3,1.682139,1.355977,1.080644,0.955786,1.684404,1.144267,1.448098,1.381354,1.495415,...,11.208333,11.083333,21.0,1.0,13.0,NaN,0.7578,40.7,99.561273,3
4,4,0.866675,0.366260,0.455986,0.425098,0.870994,0.353314,0.830158,0.652646,0.700754,...,9.625000,8.000000,19.0,1.0,13.0,30.0,0.7578,40.7,99.822774,4

In [39]:
df_AD_.head()

,Unnamed: 0_x,Slope_HPC_left,Slope_HPC_right,Slope_CING_left,Slope_CING_right,Slope_TEMP_left,Slope_TEMP_right,Slope_PARIET_left,Slope_PARIET_right,Slope_OCC_left,...,Educ,MMSE,ODQ,Country,Eurolad_code,GINI,Group,ID,Diagnosis_y,ID-unique
0,4,1.657409,1.791276,3.266917,3.692153,2.078647,1.445966,1.445989,2.056778,1.040193,...,6.0,23.74,99.524933,Argentina,ARG_F14,41.8,AD,sub-10007,1,0
1,5,1.948224,2.565999,1.030199,1.142947,1.527375,1.753363,1.041908,1.093190,1.087747,...,6.0,22.62,99.673196,Argentina,ARG_F14,41.8,AD,sub-10008,1,1
2,6,2.351906,1.582038,1.184849,1.125776,1.712991,1.561278,1.187456,1.144129,1.402591,...,15.0,25.66,99.482125,Argentina,ARG_F14,41.8,AD,sub-100013,1,2
3,7,0.973230,0.637438,2.346555,2.326625,1.785846,0.584286,2.508437,1.931204,1.449596,...,12.0,26.94,98.370155,Argentina,ARG_F14,41.8,AD,sub-100015,1,3
4,8,1.341195,2.123403,2.265030,2.556667,1.132086,1.787175,1.488300,1.638713,1.614787,...,12.0,27.90,99.606373,Argentina,ARG_F14,41.8,AD,sub-100016,1,4

In [40]:
df_FTD_.head()

,Unnamed: 0_x,Slope_HPC_left,Slope_HPC_right,Slope_CING_left,Slope_CING_right,Slope_TEMP_left,Slope_TEMP_right,Slope_PARIET_left,Slope_PARIET_right,Slope_OCC_left,...,Educ,MMSE,ODQ,Country_y,Eurolad_code_y,GINI,Group_y,ID,Diagnosis_y,ID-unique
0,0,1.155978,1.660777,2.298852,2.571176,1.868578,2.245640,2.193582,2.285243,0.895963,...,16.0,26.94,99.487845,Argentina,ARG_F14,41.4,FTD,sub-10001,1,0
1,1,1.479669,1.437262,1.396243,1.469099,1.514617,1.306546,1.439433,1.493425,1.684383,...,NaN,13.34,99.278556,Argentina,ARG_F14,41.4,FTD,sub-10002,1,1
2,1,1.479669,1.437262,1.396243,1.469099,1.514617,1.306546,1.439433,1.493425,1.684383,...,23.0,27.00,99.520497,Argentina,ARG_Tak_Martin,40.7,FTD,sub-10002,1,2
3,1,1.479669,1.437262,1.396243,1.469099,1.514617,1.306546,1.439433,1.493425,1.684383,...,NaN,13.34,99.278556,Argentina,ARG_F14,41.4,FTD,sub-10002,1,3
4,1,1.479669,1.437262,1.396243,1.469099,1.514617,1.306546,1.439433,1.493425,1.684383,...,23.0,27.00,99.520497,Argentina,ARG_Tak_Martin,40.7,FTD,sub-10002,1,4

In [41]:
df_MCI_.head()

,Unnamed: 0_x,Slope_HPC_left,Slope_HPC_right,Slope_CING_left,Slope_CING_right,Slope_TEMP_left,Slope_TEMP_right,Slope_PARIET_left,Slope_PARIET_right,Slope_OCC_left,...,Age,Educ,MMSE,ODQ,Country,Eurolad_code,GINI,Group,Diagnosis,ID-unique
0,0,1.337510,2.251347,1.233506,1.504801,1.379055,1.559732,1.618886,1.483839,1.327416,...,59,12.0,27.0,99.469512,Colombia,Col_USCO,54.800000,MCI,1,0
1,0,1.337510,2.251347,1.233506,1.504801,1.379055,1.559732,1.618886,1.483839,1.327416,...,59,5.0,23.0,99.723011,Turquia,Tur_IUEFM,43.329412,MCI,1,1
2,0,1.337510,2.251347,1.233506,1.504801,1.379055,1.559732,1.618886,1.483839,1.327416,...,59,12.0,27.0,99.469512,Colombia,Col_USCO,54.800000,MCI,1,2
3,0,1.337510,2.251347,1.233506,1.504801,1.379055,1.559732,1.618886,1.483839,1.327416,...,59,5.0,23.0,99.723011,Turquia,Tur_IUEFM,43.329412,MCI,1,3
4,1,0.915137,0.630239,0.791544,1.057216,0.682451,0.459493,1.223334,1.238947,0.782806,...,65,16.0,22.0,98.257927,Colombia,Col_USCO,54.800000,MCI,1,4

In [87]:
df_CN_.iloc[:,1 :31]

,Slope_HPC_left,Slope_HPC_right,Slope_CING_left,Slope_CING_right,Slope_TEMP_left,Slope_TEMP_right,Slope_PARIET_left,Slope_PARIET_right,Slope_OCC_left,Slope_OCC_right,...,Offset_HPC_left,Offset_HPC_right,Offset_CING_left,Offset_CING_right,Offset_TEMP_left,Offset_TEMP_right,Offset_PARIET_left,Offset_PARIET_right,Offset_OCC_left,Offset_OCC_right
0,2.859768,1.767303,2.415282,2.727924,3.081733,2.077333,2.413411,1.768170,3.129080,2.081708,...,4.851599,3.206757,4.161250,4.715357,5.535118,4.488749,4.966953,4.076689,5.791904,4.230146
1,1.309688,1.667206,1.528242,1.537064,1.376505,2.009045,1.636336,1.460334,1.433874,1.607140,...,2.010432,2.340887,2.267521,2.445618,2.373183,3.816436,3.199684,2.893094,2.758251,2.797152
2,1.257444,0.840704,1.330353,1.294367,1.342255,0.898285,1.438093,1.368015,1.307053,1.185280,...,2.268439,1.729141,2.250557,2.423744,2.679089,2.532527,3.189643,3.151721,2.838725,2.506678
3,1.682139,1.355977,1.080644,0.955786,1.684404,1.144267,1.448098,1.381354,1.495415,1.232343,...,2.704716,2.203445,2.197593,2.227333,3.130720,3.030328,3.314643,3.166422,3.164481,2.732750
4,0.866675,0.366260,0.455986,0.425098,0.870994,0.353314,0.830158,0.652646,0.700754,0.562175,...,2.080477,1.413843,1.711623,1.935030,2.457692,2.376510,2.853273,2.634403,2.520505,2.308816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,0.860623,0.726887,0.984260,0.996106,0.811934,0.623448,1.105042,1.070750,1.269507,1.034332,...,2.249643,2.407477,2.193105,2.323273,2.278166,2.492856,2.562506,2.534879,2.678311,2.442810
1385,3.240214,2.554994,4.075704,4.236230,2.822616,2.044794,3.631432,4.065509,3.820450,3.716575,...,5.725032,4.766149,6.810369,7.112332,5.180449,4.283532,6.439969,7.285327,6.601294,6.505917
1386,2.732930,2.810929,2.014831,2.376631,2.349316,2.389446,1.987368,2.083951,4.578028,3.735156,...,5.365548,5.404523,3.799749,4.340428,4.964106,4.949798,3.964125,4.146706,8.038794,6.603005
1387,3.003057,2.705750,3.486568,3.536880,2.642035,2.560009,3.293006,3.629184,3.510047,3.379987,...,5.647121,5.117362,6.176454,6.309861,5.113419,4.930625,6.010047,6.883034,6.353391,6.108625
1388,0.801384,1.119070,1.473746,1.680619,0.718336,0.731685,1.398828,1.586837,1.448785,1.551425,...,2.350267,2.519514,2.956237,3.312208,2.419884,2.264176,2.995543,3.221546,3.055521,3.123381

In [52]:
df_AD_.iloc[:, :31]

,Unnamed: 0_x,Slope_HPC_left,Slope_HPC_right,Slope_CING_left,Slope_CING_right,Slope_TEMP_left,Slope_TEMP_right,Slope_PARIET_left,Slope_PARIET_right,Slope_OCC_left,...,Offset_HPC_left,Offset_HPC_right,Offset_CING_left,Offset_CING_right,Offset_TEMP_left,Offset_TEMP_right,Offset_PARIET_left,Offset_PARIET_right,Offset_OCC_left,Offset_OCC_right
0,4,1.657409,1.791276,3.266917,3.692153,2.078647,1.445966,1.445989,2.056778,1.040193,...,3.432310,3.638717,5.588997,6.222020,4.224791,3.283389,3.358136,3.884828,2.676845,2.928099
1,5,1.948224,2.565999,1.030199,1.142947,1.527375,1.753363,1.041908,1.093190,1.087747,...,3.837539,4.773278,2.759859,2.950229,3.569434,3.664913,2.778054,2.744791,2.358694,2.431043
2,6,2.351906,1.582038,1.184849,1.125776,1.712991,1.561278,1.187456,1.144129,1.402591,...,4.869302,3.535980,3.113253,2.978254,3.872033,3.502760,3.156824,2.979909,3.123671,2.624904
3,7,0.973230,0.637438,2.346555,2.326625,1.785846,0.584286,2.508437,1.931204,1.449596,...,2.302386,1.440803,4.066361,4.058951,3.501066,1.514249,4.234739,3.291595,2.589713,1.823539
4,8,1.341195,2.123403,2.265030,2.556667,1.132086,1.787175,1.488300,1.638713,1.614787,...,3.028852,3.787523,3.920306,4.396482,3.010942,3.353690,2.896132,2.939021,3.170116,3.742848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,91,0.759163,0.279734,1.388044,1.226763,0.806634,0.099345,1.223836,0.818492,1.350326,...,2.293054,1.419434,3.039410,2.816097,2.438469,0.210621,2.880768,2.325268,2.861264,2.054698
306,92,1.792184,1.092699,3.419817,2.837302,1.620025,1.155448,3.127177,2.508397,1.912318,...,4.410748,3.751173,6.652978,5.854491,4.564787,4.230784,6.397353,5.623272,4.640817,4.290638
307,93,0.705395,0.598054,1.673441,2.030879,0.555787,0.517129,1.687339,1.858991,1.203732,...,2.383804,2.477257,3.813714,4.394934,2.309735,2.698111,4.000418,4.289530,3.010931,3.209789
308,94,1.340865,2.388338,2.063366,2.265253,1.396285,3.045822,1.379149,1.853750,1.311505,...,3.441201,5.602062,4.497591,4.842721,3.730504,6.774880,3.613070,4.318791,3.143278,3.514434
309,95,1.404514,0.893827,2.047032,1.996076,1.702345,0.940525,2.121878,2.110367,1.604344,...,3.311741,2.822568,4.712510,4.684409,3.979474,3.165277,4.869592,4.912050,3.798248,4.040712

In [53]:
df_FTD_.iloc[:, :31]

,Unnamed: 0_x,Slope_HPC_left,Slope_HPC_right,Slope_CING_left,Slope_CING_right,Slope_TEMP_left,Slope_TEMP_right,Slope_PARIET_left,Slope_PARIET_right,Slope_OCC_left,...,Offset_HPC_left,Offset_HPC_right,Offset_CING_left,Offset_CING_right,Offset_TEMP_left,Offset_TEMP_right,Offset_PARIET_left,Offset_PARIET_right,Offset_OCC_left,Offset_OCC_right
0,0,1.155978,1.660777,2.298852,2.571176,1.868578,2.245640,2.193582,2.285243,0.895963,...,2.563395,3.298595,4.264744,4.671955,3.633330,4.044234,4.266522,4.282321,2.124497,2.446361
1,1,1.479669,1.437262,1.396243,1.469099,1.514617,1.306546,1.439433,1.493425,1.684383,...,3.034175,2.693261,2.732483,2.871896,3.048578,2.661029,3.037008,2.945944,3.250395,3.058808
2,1,1.479669,1.437262,1.396243,1.469099,1.514617,1.306546,1.439433,1.493425,1.684383,...,3.034175,2.693261,2.732483,2.871896,3.048578,2.661029,3.037008,2.945944,3.250395,3.058808
3,1,1.479669,1.437262,1.396243,1.469099,1.514617,1.306546,1.439433,1.493425,1.684383,...,3.034175,2.693261,2.732483,2.871896,3.048578,2.661029,3.037008,2.945944,3.250395,3.058808
4,1,1.479669,1.437262,1.396243,1.469099,1.514617,1.306546,1.439433,1.493425,1.684383,...,3.034175,2.693261,2.732483,2.871896,3.048578,2.661029,3.037008,2.945944,3.250395,3.058808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,1,0.000178,0.000183,0.341212,0.479886,0.011640,0.000179,0.483195,0.561456,0.114990,...,-2.746594,-2.427834,0.369964,0.661239,-1.719679,-2.060482,0.831518,0.952952,-1.055039,-0.189652
97,2,1.712491,1.239579,2.034738,1.932147,1.820668,0.923051,1.933768,1.460681,1.440373,...,2.652848,2.524556,3.176218,2.867890,3.080385,2.264542,3.520832,2.667152,2.719644,2.678809
98,2,1.712491,1.239579,2.034738,1.932147,1.820668,0.923051,1.933768,1.460681,1.440373,...,2.652848,2.524556,3.176218,2.867890,3.080385,2.264542,3.520832,2.667152,2.719644,2.678809
99,3,1.087576,0.547175,1.716540,1.293418,0.876162,0.465960,1.387046,1.375306,0.759283,...,1.683573,1.144324,2.994520,2.322960,1.426342,0.706450,2.621797,2.610932,1.845111,1.408346
100,3,1.087576,0.547175,1.716540,1.293418,0.876162,0.465960,1.387046,1.375306,0.759283,...,1.683573,1.144324,2.994520,2.322960,1.426342,0.706450,2.621797,2.610932,1.845111,1.408346

In [54]:
df_MCI_.iloc[:, :31]

,Unnamed: 0_x,Slope_HPC_left,Slope_HPC_right,Slope_CING_left,Slope_CING_right,Slope_TEMP_left,Slope_TEMP_right,Slope_PARIET_left,Slope_PARIET_right,Slope_OCC_left,...,Offset_HPC_left,Offset_HPC_right,Offset_CING_left,Offset_CING_right,Offset_TEMP_left,Offset_TEMP_right,Offset_PARIET_left,Offset_PARIET_right,Offset_OCC_left,Offset_OCC_right
0,0,1.337510,2.251347,1.233506,1.504801,1.379055,1.559732,1.618886,1.483839,1.327416,...,3.365979,4.723517,2.629640,3.013884,3.642564,3.909857,3.449793,3.179781,2.995504,2.961694
1,0,1.337510,2.251347,1.233506,1.504801,1.379055,1.559732,1.618886,1.483839,1.327416,...,3.365979,4.723517,2.629640,3.013884,3.642564,3.909857,3.449793,3.179781,2.995504,2.961694
2,0,1.337510,2.251347,1.233506,1.504801,1.379055,1.559732,1.618886,1.483839,1.327416,...,3.365979,4.723517,2.629640,3.013884,3.642564,3.909857,3.449793,3.179781,2.995504,2.961694
3,0,1.337510,2.251347,1.233506,1.504801,1.379055,1.559732,1.618886,1.483839,1.327416,...,3.365979,4.723517,2.629640,3.013884,3.642564,3.909857,3.449793,3.179781,2.995504,2.961694
4,1,0.915137,0.630239,0.791544,1.057216,0.682451,0.459493,1.223334,1.238947,0.782806,...,2.360859,2.176281,1.890580,2.365986,2.098467,2.143920,2.776212,2.887655,2.260718,2.762175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,93,1.997895,1.862788,3.159962,3.144280,1.928190,1.800237,3.071476,3.190662,1.727437,...,4.323729,4.373261,5.956481,5.944666,4.267972,4.357043,5.765968,5.921645,3.764000,4.002966
476,93,1.997895,1.862788,3.159962,3.144280,1.928190,1.800237,3.071476,3.190662,1.727437,...,4.323729,4.373261,5.956481,5.944666,4.267972,4.357043,5.765968,5.921645,3.764000,4.002966
477,93,1.997895,1.862788,3.159962,3.144280,1.928190,1.800237,3.071476,3.190662,1.727437,...,4.323729,4.373261,5.956481,5.944666,4.267972,4.357043,5.765968,5.921645,3.764000,4.002966
478,93,1.997895,1.862788,3.159962,3.144280,1.928190,1.800237,3.071476,3.190662,1.727437,...,4.323729,4.373261,5.956481,5.944666,4.267972,4.357043,5.765968,5.921645,3.764000,4.002966
479,94,1.436777,1.098632,2.590858,2.446654,1.025523,1.089471,1.505783,2.339749,2.932519,...,3.979844,3.412153,5.427956,5.146925,3.518237,3.557791,3.802578,5.004029,5.857393,6.262961

In [62]:
df_CN_.iloc[:, 43:52]

,SSV_IFG_L,SSV_IFG_R,SSV_TEMP_left,SSV_TEMP_right,SSV_OCC_left,SSV_OCC_right,WMEAN_ALL,PE_ALL,FD_ALL
0,0.006332,0.005878,0.002696,0.007597,0.001630,0.006095,-0.686534,1.115442,0.858276
1,0.004393,0.006609,0.005131,0.002860,0.008439,0.004499,-0.685793,1.107025,0.770389
2,0.004991,0.012247,0.004234,0.008351,0.004922,0.004755,-0.690579,1.220202,0.928685
3,0.009637,0.010634,0.002398,0.005989,0.006487,0.008972,-0.691175,1.161459,0.868296
4,0.047744,0.044420,0.021100,0.041289,0.033726,0.039503,-0.761280,1.304064,1.329737
...,...,...,...,...,...,...,...,...,...
1384,0.039185,0.057890,0.028184,0.045887,0.023076,0.027280,-0.763815,1.323419,1.369073
1385,0.015117,0.029721,0.009227,0.020449,0.005755,0.006213,-0.704867,1.209097,1.106284
1386,0.020988,0.022166,0.017896,0.015321,0.017710,0.014295,-0.712716,1.211582,1.218559
1387,0.008930,0.008111,0.056805,0.016624,0.108049,0.106354,-0.744955,1.506019,1.242872
1388,0.049871,0.047787,0.049337,0.040588,0.028305,0.021798,-0.766217,1.315600,1.358934

In [77]:
df_CN_.iloc[:, 62:280]

,Delta_canon_EPP_ORB_left,Delta_canon_EPP_ORB_right,Delta_canon_EPP_IFG_left,Delta_canon_EPP_IFG_right,Delta_canon_EPP_MFG_left,Delta_canon_EPP_MFG_right,Delta_canon_EPP_SFG_left,Delta_canon_EPP_SFG_right,Delta_canon_EPP_HPC_left,Delta_canon_EPP_HPC_right,...,IAF_MFG_left,IAF_MFG_right,IAF_SFG_left,IAF_SFG_right,IAF_HPC_left,IAF_HPC_right,IAF_INS_left,IAF_INS_right,IAF_OCC_left,IAF_OCC_right
0,0.059161,0.070466,0.051849,0.049289,0.049934,0.047389,0.049015,0.047568,0.041415,0.056212,...,8.875,8.750,8.9375,8.8750,9.000000,8.916667,9.0,8.625,8.833333,8.791667
1,0.054096,0.047097,0.056917,0.044670,0.055201,0.042544,0.048499,0.039344,0.041028,0.037112,...,11.375,11.625,11.6875,11.6875,11.500000,11.666667,11.5,11.625,11.375000,11.500000
2,0.059660,0.051740,0.061596,0.052308,0.061998,0.046384,0.053836,0.056489,0.060980,0.045492,...,10.000,10.250,10.0625,10.0625,10.083333,9.833333,10.0,10.375,10.125000,10.166667
3,0.058654,0.056826,0.060448,0.056367,0.068132,0.053792,0.067543,0.045742,0.058767,0.039325,...,11.250,11.125,11.1875,11.0625,11.166667,10.916667,11.0,10.875,11.208333,11.083333
4,0.043061,0.042042,0.045694,0.039943,0.045708,0.036764,0.039002,0.036255,0.044407,0.037282,...,8.000,8.500,8.0000,8.6875,10.083333,9.166667,8.0,9.500,9.625000,8.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,0.035464,0.035469,0.035834,0.034404,0.030824,0.030423,0.031417,0.031326,0.038548,0.033387,...,8.000,10.000,8.0000,8.5625,8.000000,12.000000,8.0,10.000,8.000000,9.041667
1385,0.054815,0.048826,0.049235,0.049774,0.044013,0.046808,0.044252,0.046730,0.053651,0.049409,...,8.000,8.875,8.3125,8.5000,8.750000,9.666667,8.5,9.250,8.958333,9.625000
1386,0.044759,0.052309,0.042457,0.046901,0.038112,0.037699,0.038526,0.039239,0.049349,0.049044,...,9.125,8.500,9.2500,9.0625,8.666667,8.583333,9.0,9.000,8.958333,8.000000
1387,0.059905,0.064894,0.052238,0.051449,0.039586,0.041117,0.042107,0.041310,0.050399,0.052534,...,8.000,8.000,9.0625,9.0000,9.333333,8.583333,8.5,8.625,9.916667,9.708333
1388,0.032594,0.038136,0.030101,0.036569,0.035927,0.034773,0.033520,0.034468,0.034192,0.042244,...,8.625,9.500,8.0000,9.1875,8.500000,8.833333,8.0,9.625,9.166667,8.833333

In [88]:
metrics_freq = df_CN_.iloc[:, 62:280].columns.tolist()
metrics_aperiodic = df_CN_.iloc[:, 1:31].columns.tolist()
metrics_complex = df_CN_.iloc[:, 43:52].columns.tolist()

In [85]:
X_CN = df_CN_[metrics_freq]
X_AD = df_AD_[metrics_freq]
X_FTD = df_FTD_[metrics_freq]
X_MCI = df_MCI_[metrics_freq]

In [89]:
X_CN = df_CN_[metrics_aperiodic]
X_AD = df_AD_[metrics_aperiodic]
X_FTD = df_FTD_[metrics_aperiodic]
X_MCI = df_MCI_[metrics_aperiodic]

In [91]:
X_CN = df_CN_[metrics_complex]
X_AD = df_AD_[metrics_complex]
X_FTD = df_FTD_[metrics_complex]
X_MCI = df_MCI_[metrics_complex]